version: "3"

services:
  biz_service_backend1:
    build:
      context: .
      dockerfile: Dockerfile
    image: biz_service_backend
    ports:
      - "8808:8808"
    environment:
      TZ: Asia/Shanghai
      MY_HOST: 192.168.2.225
      MYSQL_HOST: 192.168.2.225
      MYSQL_PORT: 3306
      REDIS_HOST: 192.168.2.225
      REDIS_PORT: 6379
      USER_12_ADDR: 192.168.2.225:8808
      USER_123_ADDR: 192.168.2.225:8809
      USER_1234_ADDR: 192.168.2.225:8810
      DEFAULT: 10.26.70.18:10888
      EXCHANGE: 10.26.70.18:80
      USERID: 12
    volumes:
      - ./manifest/config/config-online.yaml:/app/manifest/config/config-online.yaml      # 挂载配置文件
    command: ["sh","service.sh","startonline"]
    depends_on:
      - redis1
      - mysql1
  
  redis1:
    image: redis:latest
    restart: always
#    volumes:
#    - ./repos/redis/data:/data:rw    # 数据持久化
    ports:
      - "6379:6379"

  mysql1:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./resource/co_data:/docker-entrypoint-initdb.d
      - ./manifest/docker/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"



