version: "3"

services:
  biz_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: biz_service_backend
    container_name: biz_service_backend
    ports:
      - "8808:8808"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./manifest/config/config-offline.yaml:/app/manifest/config/config-offline.yaml      # 挂载配置文件
    command: ["./main"]
    depends_on:
      - redis    # 声明服务依赖
  
  redis:
    image: redis:latest
    container_name: biz_redis
    restart: always
#    volumes:
#    - ./repos/redis/data:/data:rw    # 数据持久化
    ports:
      - "6379:6379"




