version: "3"

services:
  biz_service_backend3:
    build:
      context: .
      dockerfile: Dockerfile
    image: biz_service_backend
    ports:
      - "8810:8808"
    environment:
      TZ: Asia/Shanghai
      MY_HOST: 192.168.2.225
      MYSQL_HOST: 192.168.2.225
      MYSQL_PORT: 3308
      REDIS_HOST: 192.168.2.225
      REDIS_PORT: 6381
      USER_12_ADDR: 127.0.0.1:8808
      USER_123_ADDR: 127.0.0.1:8809
      USER_1234_ADDR: 127.0.0.1:8810
      DEFAULT: 10.26.70.18:10888
      EXCHANGE: 10.26.70.18:80
    volumes:
      - ./manifest/config/config-offline.yaml:/app/manifest/config/config-offline.yaml      # 挂载配置文件
    command: ["sh","service.sh","startonline"]
    depends_on:
      - redis3
      - mysql3
  
  redis3:
    image: redis:latest
    restart: always
#    volumes:
#    - ./repos/redis/data:/data:rw    # 数据持久化
    ports:
      - "6381:6379"

  mysql3:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_data3:/var/lib/mysql  # 数据持久化
      - ./resource/hosp_data:/docker-entrypoint-initdb.d
      - ./manifest/docker/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3306"


volumes:
  mysql_data3:

